### ISSUE TITLE
二维码下载网页打开不了

### ISSUE THREAD

**Issue by starplatinum3** [MrHGJ/FlutterGithub#3]
你好，我这里扫码下载网页打开不了，在微信、钉钉、夸克浏览器里都试过了，二维码的链接是这个，我看貌似是小米的，是不是只有小米才能下载啊，我是荣耀9x
https://pan.mioffice.cn/link/A18A953835E391D9AC060975AEE13110

**Comment by MrHGJ-test** [comment]
已更新下载链接

**Comment by MrHGJ** [comment]
已更新下载链接
